# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use official Python slim image
FROM python:3.11-slim

# Install ffmpeg for video processing
RUN apt-get update \
    && apt-get install -y --no-install-recommends ffmpeg \
    && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Copy project files
COPY pyproject.toml requirements.txt README.md ./
COPY src ./src

# Install dependencies and server
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir .

# Default entrypoint for stdio server
ENTRYPOINT ["video-edit-mcp"]
